- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Atlas
  - Amber
  # - Bagel
  # - Box # Sandwich Station, WIP, can be used but is not done.
  - Cluster
  # - Cog # BROKEN, DONT USE
  # - Core
  - Fland
  # - Gate
  # - Loop
  # - Marathon
  # - Meta
  # - Oasis # BROKEN, DONT USE
  - Omega
  # - Origin # BROKEN, DONT USE
  - Saltern
  - Packed
  - Reach
  - Train
  # - FlandHighPop
  # - OasisHighPop
  # - Barratry
  # - Kettle
  - Submarine
  # - Leonid
  - Elkridge # ShibaStation - Elkridge
